version: '3.9'

services:
  business-persistence:
    build: .
    container_name: business-persistence
    ports:
      - "${PORT}:8080"
    environment:
      - DbSettings__ConnectionString=${DbSettings__ConnectionString}
    restart: always
